'''Q.2- Name and handle the exception occurred in the following program: 
l=[1,2,3]
print(l[3])
'''
Ans.2- Name of the exception is "IndexError"
try:
    l=[1,2,3]
    print(l[3])
except IndexError:
    print("Exception",IndexError)
