Q.3- What will be the output of the following code:

# Program to depict Raising Exception
 
try:
    raise NameError("Hi there")  # Raise Error
except NameError:
    print "An exception"
    raise  # To determine whether the exception was raised or not

Ans.3- An exception
Traceback (most recent call last):
  File "C:\Users\Samyak\Desktop\Assignment12\A.py", line 2, in <module>
    raise NameError("Hi there")  # Raise Error
NameError: Hi there
